Vagrant.configure("2") do |config|

    config.vm.define "build" do |build|
      build.vm.box = "ubuntu/trusty64"
      build.vm.hostname = 'build'
      build.vm.network :private_network, ip: "192.168.50.10"
      build.vm.network "forwarded_port", host: 5601, guest: 5601
      build.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
      end
    end
  end
